---
- name: call middleware
  hosts: localhost
  gather_facts: no
  vars:
    #api_endpoint: http://camel-infra-dm-route-intelli-infra-apps.apps.ocp-jaguar.ocpinfinity.com/service/host/reboot/
    api_endpoint: http://node3:8080/service/host/reboot
  tasks:
    - debug:
        msg: "API call to {{ nodes }}"
        #verbosity: 1
    - name: Create the API body
      set_fact:
        api_body: "{{ api_body | default([]) | union([{'host': item}]) }}"
      loop: "{{ nodes }}"
    - name: Update the API body
      set_fact:
        api_body: "{{ {'hosts' : api_body} }}"
    - debug:
        msg: "{{ api_body }}"
        #verbosity: 1
    - name: Make the API call
      uri:
        url: "{{ api_endpoint }}"
        method: POST
        body_format: json
        body: "{{ api_body }}"
      register: return_data
    - debug:
        msg: "{{ return_data }}"

    - name: Collect devices that need reboot
      set_fact:
        failed_nodes: "{{ nodes|default([]) + [ item.host ] }}"
      loop: "{{ return_data.json }}"
      when: item.restart

    - name: Nodes with failures
      set_stats:
        data:
          reboot_nodes: "{{ failed_nodes }}"
      when: failed_nodes is defined

    - name: Collect devices that were recently rebooted
      set_fact:
        recent_nodes: "{{ nodes|default([]) + [ item.host ] }}"
      loop: "{{ return_data.json }}"
      when: not item.restart

    - name: Display nodes that will not be restarted
      debug:
        msg: "{{ recent_nodes }}"
      when: recent_nodes is defined
